### ISSUE TITLE
fix markup types

### ISSUE THREAD

**Issue by LFSaw** [3DMIN/3DMIN.github.io#1]
```
<span class="note">for the following steps it is recommended to work in pairs of two</span>
```

<img width="648" alt="screen shot 2016-03-19 at 21 27 03" src="https://cloud.githubusercontent.com/assets/75468/13901111/64855428-ee19-11e5-9df5-fec746bd69ab.png">

**Comment by pppws** [comment]
(bleibt man hier englisch?)
komme erst morgen vormittag dazu. denke bis mittag ist das bis auf den firefix-bug drin!

**Comment by pppws** [comment]
die auszeichnungen sind wie besprochen drin.

```
## h2
**bold** – fett, auszeichnung im fließtext
*em* – kursiv, fließtext und/oder bildunterschriften
<span class="note"></span> – weißer rahmen um text, hinweis
{% highlight LANGUAGE %}
{% endhighlight %} – code, language mit jeweiliger sprache ersetzen (html, ruby, etc)
```

**Comment by LFSaw** [comment]
danke!
englisch: ist recht egal... ja für uns nur, irgendwie. Ich schreibe solche sachen eher in englisch, hoffe das ist ok.
