### ISSUE TITLE
move cover images to "Bilder", add an identifier to page slug.

### ISSUE THREAD

**Issue by LFSaw** [3DMIN/3DMIN.github.io#2]
```

---
title: box
order: 4
layout: page-build
cover: "../Bilder/box-cover.jpg"

---

[…]
```

**Comment by pppws** [comment]
teaser and cover images moved to /images
in /images are folders named after the build-chapter (e.g. bellow). place the teaser and cover image here: chaptername-cover.jpg -> (e.g. bellow-cover.jpg)

**Comment by LFSaw** [comment]
kewl
