### ISSUE TITLE
add missing photos

### ISSUE THREAD

**Issue by amelie030** [3DMIN/3DMIN.github.io#33]
+ [x] painting
    + [x] IMG_4477.jpg above "workspace"
+ [x] bellow
    + [x] picture of workspace
    + [x] picture of punching holes >> 1586
+ [x] legstraps
  + [x] end result
  + [x] TODO photos  
+ [x] mainboard
  + [x] Materials >> 1602
  + [x] build cables thumb to main and fingers to main 
+ [x] valves mounting
  + [x] Endresult with both cirquits
+ [x] toppart-mounting (photos maybe on 3dmini)
  + [x] title photo
  + [x] Clip capacative finger sensors into the fingerboard.
  + [x] Thread cables of capacative finger sensors through the hole in the handpiece top and press the sensor board into its cavity.
  + [x] fingerboard to part with metal rails
  + [x] handpiece to part with metal rails
  + [x] Put all of the above on top of upper frame
  + [x] This sandwich constrution then needs to be attached to bellow
+ [x] final assembly
  + [x] all photos

**Comment by LFSaw** [comment]
here is the list of photos:

https://piratenpad.de/p/OpbYT7Gz
