### ISSUE TITLE
mainboard (Till + Dominik)

### ISSUE THREAD

**Issue by amelie030** [3DMIN/3DMIN.github.io#45]
+ [x] photo tools and material löschen
+ [x] note: euro circuits
+ [x] Bildunterschriften (Dominik)
+ [x] kicad file vom mainboard hinzufügen
+ [x] Kommentar zum xosc hinzufügen
+ [x] xosc in partlist einfügen
+ [x] capazitive Sensoren hinzufügen (order und stecker löten)
+ [x] Verkabelung

**Comment by LFSaw** [comment]
relates to #56.

**Comment by LFSaw** [comment]
add order parameters
