### ISSUE TITLE
helper board (Dominik)

### ISSUE THREAD

**Issue by amelie030** [3DMIN/3DMIN.github.io#49]
Löterei aus encoder kapitel kopieren
Kommentar allgemein zu Löten
Kommentar zu Hardlist
Untertitel Bilder
LED Platine mit rein nehmen 
arduino chip upload hinzufügen
illustrater files zu helperboards verlinken
Kommentar zum ätzen

**Comment by LFSaw** [comment]
illustrater files zu helperboards verlinken -- done.

**Comment by dhmlGIT** [comment]
löten und ätzen und upload arduino code geschrieben. einige TO DOs eingefügt. für zusätzliche bilder unds  verlinkungen.
