### ISSUE TITLE
broken frontend of any build section

### ISSUE THREAD

**Issue by LFSaw** [3DMIN/3DMIN.github.io#6]
in difference to my local version, the uploaded one looks broken in Firefox and Safari.

![screen shot 2016-04-05 at 18 22 19](https://cloud.githubusercontent.com/assets/75468/14289501/5be0349c-fb5b-11e5-995f-017f00b05262.jpg)
http://3dmin.github.io/build/cables.html

**Comment by pppws** [comment]
table of content bug. looking into it on monday.

**Comment by LFSaw** [comment]
aaaaand?

**Comment by pppws** [comment]
ooops.
i accidently implemented a plug-in to generate the tabel of content. 

note myself: https://css-tricks.com/automatic-table-of-contents/

**Comment by pppws** [comment]
fixed
