### ISSUE TITLE
add general info on front page

### ISSUE THREAD

**Issue by amelie030** [3DMIN/3DMIN.github.io#61]
The PushPull SE (student edition) which is presented here was developed for a student workshop within the 3DMIN research project. It is the third iteration of the PushPull Instrument. This homepage serves several purposes:

Firstly, it is a fine grained documentation of the development and building process to conserve our research results and present them to the public. Sharing our knowledge with others felt consistent, since the 3DMIN project was funded by the Einstein Stiftung Berlin. 

Secondly, the information presented on this page can be used to build your own PushPull. Before you start doing so, be aware of the following facts:

- PushPull is handmade product. You should be experienced in: building and soldering electronic circuits, programming, working with rapid prototyping tools. 
- Having some patience and willingness to tinker and in case redo some steps to get a good result might be helpful.
- PushPull was designed in a way to be able to produce it in house with the facilities, workshops and tools available for us. For example: Lasercutter, 3D printer, wood- and metal-workshop, PCB etching tools (laser and 3D printing files are provided within each working step).
- Some parts were produced externally by professional manufactors (multilayer PCBs, metal frame). We would highly recommend to do so for the indicated parts.  

also our documentation might be used as inspiration. We would be more than happy to learn about individual variations or push pull inspired instruments. 

If you feel like getting a face to face introduction on building this extraordinary instrument as well as to be introduced to the development of new sound patches and mappings, don’t hesitate to contact us. As we accomplished PushPull workshops in the past we are definitely in repeating such format one way or the other.

please get in touch,

Your 3DMIN - PushPull - Team (Till Bovermann, Amelie Hinrichsen, Dominik Hildebrand Marques Lopes)

**Comment by LFSaw** [comment]
added some text (see front page and disclaimer)
